/**
 * First paragraph of the English Wikipedia article for each U.S. state (and D.C.).
 * Source: MediaWiki API (intro extract). Regenerate: `node fetch-state-notes.mjs`
 */
export const stateNotes = {
  Alabama:
    'Alabama ( , AL-ə-BAM-ə) is a state in the Southeastern and Deep Southern regions of the United States. It borders Tennessee to the north, Georgia to the east, Florida and the Gulf of Mexico to the south, and Mississippi to the west. Alabama is the 30th largest by area, and the 24th-most populous of the 50 U.S. states. Alabama is nicknamed the Yellowhammer State, after the state bird. Alabama is also known as the "Heart of Dixie" and the "Cotton State". The state has diverse geography, with the north dominated by the mountainous Tennessee Valley and the south by Mobile Bay, a historically significant port. Alabama\'s capital is Montgomery, and its largest city by population and area is Huntsville. Its oldest city is Mobile, founded by French colonists (Alabama Creoles) in 1702 as the capital of French Louisiana.',
  Alaska:
    "Alaska ( ə-LASS-kə) is a non-contiguous U.S. state located in the northwestern regions of North America. Part of the Western United States region, it is one of the two non-contiguous U.S. states, alongside Hawaii. Alaska is considered to be the northernmost, westernmost, and, longitudinally, the easternmost state in the United States. It is a semi-exclave of the U.S., bordering the Canadian territory of Yukon and the province of British Columbia to the east. It shares a western maritime border in the Bering Strait with Russia's Chukotka Autonomous Okrug, and is closer to another continent (Asia) than any other U.S. state. The Chukchi and Beaufort Seas of the Arctic Ocean lie to the north, and the Pacific Ocean to the south.",
  Arizona:
    "Arizona is a landlocked state in the Southwestern United States, sharing the Four Corners region with Colorado, New Mexico, and Utah. It also borders Nevada to the northwest and California to the west, and shares an international border with the Mexican states of Sonora and Baja California to the south and southwest. Its capital and largest city is Phoenix, which is the most populous state capital and fifth-most populous city in the United States. Arizona is divided into 15 counties. Arizona is the sixth-largest state by area and the 14th-most-populous of the 50 states. It is the 48th state and last of the contiguous states to be admitted to the Union, achieving statehood on February 14, 1912. Historically part of the territory of Alta California and Nuevo México in New Spain (Spanish Empire), it became part of independent Mexico in 1821.",
  Arkansas:
    "Arkansas ( , AR-kən-saw) is a landlocked state in the West South Central region of the Southern United States. It borders Missouri to the north, Tennessee and Mississippi to the east, Louisiana to the south, Texas to the southwest, and Oklahoma to the west. Its name derives from the Osage language, and refers to their relatives, the Quapaw people. The state's diverse geography ranges from the mountainous regions of the Ozark and Ouachita Mountains, which make up the U.S. Interior Highlands, to the densely forested land in the south known as the Arkansas Timberlands, to the eastern lowlands along the Mississippi River and the Arkansas Delta. Previously part of French Louisiana and the Louisiana Purchase, the Territory of Arkansas was admitted to the Union as the 25th state on June 15, 1836.",
  California:
    "California () is a state in the Western United States that lies on the Pacific Coast. It borders Oregon to the north, Nevada and Arizona to the east, and shares an international border with the Mexican state of Baja California to the south. With almost 40 million residents across an area of 163,696 square miles (423,970 km2), it is the largest state by population, third-largest state by area and the largest state economy in the U.S., with a GDP of approximately $4.3 trillion. Prior to European colonization, California was one of the most culturally and linguistically diverse areas in pre-Columbian North America. European exploration in the 16th and 17th centuries led to the colonization by the Spanish Empire. The area became a part of Mexico in 1821, as a result of its successful war for independence.",
  Colorado:
    "Colorado is a landlocked state in the Mountain West subregion of the Western United States. It is one of the Mountain states, and part of the Southwestern United States, sharing the Four Corners region with Arizona, New Mexico, and Utah. It is also bordered by Wyoming to the north, Nebraska to the northeast, Kansas to the east, and Oklahoma to the southeast. Colorado is noted for its landscape of mountains, forests, high plains, mesas, canyons, plateaus, rivers, and desert lands. It encompasses most of the Southern Rocky Mountains, as well as the northeastern portion of the Colorado Plateau and the western edge of the Great Plains. Colorado is the eighth-largest U.S. state by area and the 20th by population. The United States Census Bureau estimated the population of Colorado to be 5,957,493 as of July 1, 2024, a 3.2% increase from the 2020 United States census.",
  Connecticut:
    "Connecticut ( kə-NET-ih-kət) is a state in the New England region of the Northeastern United States. It borders Rhode Island to the east, Massachusetts to the north, New York to the west, and Long Island Sound to the south. Its capital is Hartford, and its most populous city is Bridgeport. Connecticut lies between the major hubs of New York City and Boston along the Northeast Corridor, where the New York-Newark Combined Statistical Area, which includes four of Connecticut's seven largest cities, extends into the southwestern part of the state. Connecticut is the third-smallest state by area after Rhode Island and Delaware, and the 29th-most populous with more than 3.6 million residents as of 2024, ranking it fourth among the most densely populated U.S. states.",
  Delaware:
    "Delaware ( DEL-ə-wair) is a state in the Mid-Atlantic and South Atlantic regions of the United States. It borders Maryland to its south and west, Pennsylvania to its north, New Jersey to its northeast, and the Atlantic Ocean to its east. The state's name derives from the adjacent Delaware Bay, which in turn was named after Thomas West, 3rd Baron De La Warr, an English nobleman and the Colony of Virginia's first colonial-era governor. Delaware occupies the northeastern portion of the Delmarva Peninsula, and some islands and territory within the Delaware River. It is the second-smallest and sixth-least populous state, but also the sixth-most densely populated. Delaware's most populous city is Wilmington, and the state's capital is Dover, the second-most populous city in Delaware.",
  "District of Columbia":
    "Washington, D.C., officially the District of Columbia and commonly known as simply Washington or D.C., is the capital city and federal district of the United States. The city is on the Potomac River across from Virginia and shares land borders with Maryland to its north and east. It was named after George Washington, a Founding Father and the first president of the United States. The district is named for Columbia, the female personification of the nation, through which human form and attributes are applied to the United States. The U.S. Constitution in 1789 called for the creation of a federal district under exclusive jurisdiction of the U.S. Congress. As such, Washington, D.C., is not part of any state, and is not one itself. The Residence Act, adopted on July 16, 1790, approved the creation of the capital district along the Potomac River, and is considered the city's founding date.",
  Florida:
    "Florida ( FLORR-ih-də; Spanish: [floˈɾiða] ) is a state in the Southeastern and South Atlantic regions of the United States. It borders the Gulf of Mexico to the west, Alabama to the northwest, Georgia to the north, the Atlantic Ocean to the east, the Straits of Florida to the south, and The Bahamas to the southeast. About two-thirds of Florida occupies a peninsula between the Gulf of Mexico and the Atlantic Ocean. It has the longest coastline in the contiguous United States, spanning approximately 1,350 miles (2,170 km), not including its many barrier islands. It is the only state that borders both the Gulf of Mexico and the Atlantic Ocean. With a population of over 23 million, it is the third-most populous state in the United States and ranks seventh in population density as of 2020. Florida spans 65,758 square miles (170,310 km2), ranking 22nd in area among the states.",
  Georgia:
    "Georgia ( JOR-jə) is a state in the Southeastern, South Atlantic, and Deep South regions of the United States. It borders Tennessee to the northwest, North Carolina and South Carolina to the northeast, the Atlantic Ocean to the east, Florida to the south, and Alabama to the west. Of the 50 U.S. states, Georgia is the 24th-largest by area and eighth-most populous. According to the U.S. Census Bureau, its 2025 estimated population was 11,302,748. Atlanta, a global city, is both the state's capital and its largest city. The Atlanta metropolitan area, with a population greater than 6.3 million people in 2023, is the eighth most populous metropolitan area in the United States and contains about 57% of Georgia's entire population. Other major metropolitan areas in the state include Augusta, Savannah, Columbus, and Macon.",
  Hawaii:
    "Hawaii ( hə-WY-ee; Hawaiian: Hawaiʻi [həˈvɐjʔi, həˈwɐjʔi]) is an island state of the United States, in the Pacific Ocean about 2,000 miles (3,200 km) southwest of the U.S. mainland. One of the two non-contiguous U.S. states (along with Alaska), it is the only state not on the North American mainland, the only state that is an archipelago, the only state south of the Tropic of Cancer, one of only two states, along with Florida, with regions that have a tropical climate, and one of the two U.S. states, along with Texas, that were internationally recognized sovereign countries before becoming U.S. states. Hawaii consists of 137 volcanic islands that make up almost the entire Hawaiian archipelago (the exception is Midway Atoll). Spanning 1,500 miles (2,400 km), the state is physiographically and ethnologically part of the Polynesian subregion of Oceania.",
  Idaho:
    "Idaho ( , EYE-də-hoe) is a landlocked state in the Pacific Northwest and Mountain West subregions of the Western United States. It borders Montana and Wyoming to the east, Nevada and Utah to the south, and Washington and Oregon to the west; the state shares a small portion of the Canada–United States border to the north with the Canadian province of British Columbia. Idaho's state capital and largest city is Boise. With an area of 83,569 square miles (216,440 km2), Idaho is the 14th-largest state by land area. The state has a population of approximately two million people; it ranks as the 13th-least populous and the seventh-least densely populated of the 50 U.S. states. For thousands of years, and prior to European colonization, Idaho had been inhabited by natives.",
  Illinois:
    "Illinois ( IL-ih-NOY) is a state in the Midwestern region of the United States. It borders on Lake Michigan to its northeast, the Mississippi River to its west, and the Wabash and Ohio rivers to its south. Of the fifty U.S. states, Illinois has the fifth-largest gross domestic product (GDP), the sixth-largest population, and the 25th-most land area. Its capital city is Springfield in the center of the state, and the state's largest city is Chicago in the northeast. Present-day Illinois was inhabited by Indigenous cultures for thousands of years. The French were the first Europeans to arrive, settling near the Mississippi and Illinois rivers in the 17th century Illinois Country, as part of their sprawling colony of New France. A century later, the revolutionary war Illinois campaign prefigured American involvement in the region.",
  Indiana:
    "Indiana ( IN-dee-AN-ə) is a state in the Midwestern region of the United States. It borders Lake Michigan to the northwest, Michigan to the north and northeast, Ohio to the east, the Ohio River and Kentucky to the south and southeast, and the Wabash River and Illinois to the west. Nicknamed \"the Hoosier State\", Indiana is the 38th-largest by area and the 17th-most populous of the 50 states. The state's capital and largest city is Indianapolis. Indiana was admitted to the Union as the 19th state on December 11, 1816. Indigenous resistance to American settlement was broken with their defeat in Battle of Tippecanoe in 1811, and the collapse of Tecumseh's confederacy in 1813. The new settlers were primarily Americans of British ancestry from the eastern seaboard and the Upland South, and Germans.",
  Iowa: "Iowa ( EYE-ə-wə) is a landlocked state in the upper Midwestern region of the United States. It borders the Mississippi River to the east and the Missouri River and Big Sioux River to the west; Wisconsin to the northeast, Illinois to the east and southeast, Missouri to the south, Nebraska to the west, South Dakota to the northwest, and Minnesota to the north. Iowa is the 26th largest in total area and the 31st most populous of the 50 U.S. states, with a population of 3.19 million. The state's capital, most populous city, and largest metropolitan area fully located within the state is Des Moines. During the 18th and early 19th centuries, Iowa was a part of French Louisiana and Spanish Louisiana; its state flag is patterned after the flag of France. After the Louisiana Purchase, pioneers laid the foundation for an agriculture-based economy in the heart of the Corn Belt.",
  Kansas:
    "Kansas ( KAN-zəss) is a landlocked state in the Midwestern region of the United States. It borders Nebraska to the north; Colorado to the west; Oklahoma to the south; and Missouri to the east. Kansas is named after the Kansas River, in turn named after the Kansa people. Its capital is Topeka, and its most populous city is Wichita; however, the largest urban area is the bi-state Kansas City metropolitan area surrounding Kansas City, Missouri, which straddles the border of Kansas and Missouri. For thousands of years, what is now known as Kansas was home to numerous and diverse Indigenous tribes. The first settlement of non-indigenous people in Kansas occurred in 1827 at Fort Leavenworth. The pace of settlement accelerated in the 1850s, in the midst of political wars over the slavery debate.",
  Kentucky:
    "Kentucky (US: , UK: ), officially the Commonwealth of Kentucky, is a landlocked state in the Southeastern region of the United States. It borders Illinois, Indiana, and Ohio to the north, West Virginia to the northeast, Virginia to the east, Tennessee to the south, and Missouri to the west. Its northern border is defined by the Ohio River. Its capital is Frankfort and its most populous city is Louisville. As of 2024, the state's population was approximately 4.6 million. Previously a part of colonial Virginia, Kentucky was admitted into the Union as the fifteenth state on June 1, 1792. It is known as the \"Bluegrass State\" in reference to Kentucky bluegrass, a species of grass introduced by European settlers, which has long supported the state's thoroughbred horse industry.",
  Louisiana:
    "Louisiana (French: Louisiane; Spanish: Luisiana [lwiˈsjana]; Louisiana Creole: Lwizyàn) is a state in the Deep South and South Central regions of the United States. It is bordered by Texas to the west, Arkansas to the north, and Mississippi to the east. Of the 50 U.S. states, it ranks 31st in area and 25th in population, with roughly 4.6 million residents. Reflecting its French heritage, Louisiana is the only U.S. state with political subdivisions termed parishes, which are equivalent to counties, making it one of only two U.S. states not subdivided into counties (the other being Alaska and its boroughs). Baton Rouge is the state's capital, and New Orleans, a French Louisiana region, is its most populous city with a population of about 363,000 people.",
  Maine:
    "Maine ( MAYN) is a state in the New England region of the United States, and the northeasternmost state in the contiguous United States. It borders New Hampshire to the west, the Gulf of Maine to the southeast, and the Canadian provinces of New Brunswick and Quebec to the northeast and northwest, and shares a maritime border with Nova Scotia. It is the only state to border only one other state, which is New Hampshire. Maine is the largest state in New England by total area, almost as large as the combined area of the remaining five states. Of the 50 U.S. states, it is the 12th-smallest by area, the 9th-least populous, the 13th-least densely populated, and the most rural. As of 2024, Maine's population stood at a Census-estimated 1,400,000, the state's highest-ever population estimate. Maine's capital is Augusta, while its most populous city is Portland.",
  Maryland:
    "Maryland (US: ) is a state in the Mid-Atlantic and Southern regions of the United States. It borders Virginia to its south, West Virginia to its west, Pennsylvania to its north, and Delaware to its east, as well as with the Atlantic Ocean to its east, and the national capital and federal district of Washington, D.C. to the southwest. With a total area of 12,407 square miles (32,130 km2), Maryland is the ninth-smallest state by land area, and its population of 6.1 million ranks it the 19th-most populous state and the fifth-most densely populated. Maryland's capital city is Annapolis, and the state's most populous city is Baltimore. Maryland's coastline was first explored by Europeans in the 16th century. Prior to that, it was inhabited by several Native American tribes, mostly the Algonquian peoples.",
  Massachusetts:
    "Massachusetts ( MASS-ə-CHOO-sits, -⁠zits; Massachusett: Muhsachuweesut [məhswatʃəwiːsət]), officially the Commonwealth of Massachusetts, is a state in the New England region of the Northeastern United States. It borders the Atlantic Ocean and the Gulf of Maine to its east, Connecticut and Rhode Island to its south, New Hampshire and Vermont to its north, and New York to its west. Massachusetts is the seventh-smallest state by land area. With an estimated population of over 7.1 million, it is the most populous state in New England (with nearly half of all New Englanders residing in Massachusetts), the 16th-most-populous in the United States, and the third-most densely populated U.S. state after New Jersey and Rhode Island. Massachusetts was a site of early English colonization. The Plymouth Colony was founded in 1620 by the Pilgrims of Mayflower.",
  Michigan:
    "Michigan ( MISH-ig-ən) is a peninsular state in the Great Lakes region of the Upper Midwestern United States. It shares water and land boundaries with Minnesota to the northwest, Wisconsin to the west, Indiana and Illinois to the southwest, Ohio to the southeast, and the Canadian province of Ontario to the east, northeast and north. With a population of 10.14 million and an area of 96,716 sq mi (250,490 km2), Michigan is the tenth-largest state by population, the 11th-largest by area, and the largest by total area east of the Mississippi River. The state capital is Lansing, while its most populous city is Detroit. The Metro Detroit region in Southeast Michigan is among the nation's most populous and largest metropolitan economies. Other important metropolitan areas include Grand Rapids, Flint, Ann Arbor, Kalamazoo, the Tri-Cities, and Muskegon.",
  Minnesota:
    'Minnesota is a state in the Upper Midwestern region of the United States. It is bordered by the Canadian provinces of Manitoba and Ontario to the north and east and by the U.S. states of Wisconsin to the east, Iowa to the south, and North Dakota and South Dakota to the west. The northeast corner has a water boundary with Michigan. It is the 12th-largest U.S. state in area and the 22nd-most populous, with about 5.8 million residents. Minnesota is known as the "Land of 10,000 Lakes"; it has 14,420 bodies of fresh water covering at least ten acres each. Roughly a third of the state is forested. Much of the remainder is prairie and farmland. More than 60% of Minnesotans (about 3.',
  Mississippi:
    "Mississippi ( MISS-iss-IP-ee) is a state in the Southeastern and Deep South regions of the United States. It borders Tennessee to the north, Alabama to the east, the Gulf of Mexico to the south, Louisiana to the southwest, and Arkansas to the northwest. Mississippi's western boundary is largely defined by the Mississippi River, or its historical course. Mississippi is the 32nd largest by area and 35th-most populous of the 50 U.S. states and has the lowest per-capita income. Jackson is both the state's capital and largest city. Greater Jackson is the state's most populous metropolitan area, with a population of 591,978 in 2020. Other major cities include Gulfport, Southaven, Hattiesburg, Biloxi, Olive Branch, Tupelo, Meridian, and Greenville.",
  Missouri:
    "Missouri (see pronunciation) is a landlocked state in the Midwestern region of the United States. Ranking 21st in land area, it borders Iowa to the north, Illinois, Kentucky and Tennessee to the east, Arkansas to the south and Oklahoma, Kansas, and Nebraska to the west. With over six million residents, it is the 19th-most populous state of the country. The largest urban areas are St. Louis, Kansas City, Springfield, and Columbia. The capital is Jefferson City. Humans have inhabited present-day Missouri for at least 12,000 years. The Mississippian culture, which emerged in the ninth century, built cities with pyramidal and other ceremonial mounds before declining in the 14th century. The Indigenous Osage and Missouria nations inhabited the area when European people arrived in the 17th century. The French incorporated the territory into Louisiana, founding Ste.",
  Montana:
    "Montana ( mon-TAN-ə) is a landlocked state in the Mountain West subregion of the Western United States. It is bordered by Idaho to the west, North Dakota to the east, South Dakota to the southeast, Wyoming to the south, and the Canadian provinces of Alberta, British Columbia, and Saskatchewan to the north. It is the fourth-largest state by area, but the eighth-least populous state and the third-least densely populated state. Its capital is Helena, while the most populous city is Billings. The western half of the state contains numerous mountain ranges, particularly the Rocky Mountains, while the eastern half is characterized by western prairie terrain and badlands, with smaller mountain ranges found throughout the state. Most of Montana came under American sovereignty with the Louisiana Purchase from France in 1803 and was explored by the Lewis and Clark Expedition shortly thereafter.",
  Nebraska:
    "Nebraska ( nə-BRASS-kə) is a triple-landlocked state in the Midwestern region of the United States. It borders South Dakota to the north; Wyoming to the west; Colorado to the southwest; Kansas to the south; and Missouri to the southeast and Iowa to the east, both across the Missouri River. Nebraska is the 16th-largest state by land area, with just over 77,347 square miles (200,330 km2). As of the 2020 census, the population was 1,961,504, and was estimated to be 2,018,006 in 2025, it is the 38th-most populous state and the eighth-least densely populated. Nebraska's capital is Lincoln, and its most populous city is Omaha, which is on the Missouri River. Nebraska was admitted into the United States in 1867, two years after the end of the American Civil War.",
  Nevada:
    'Nevada ( nə-VAD-ə; Spanish: [neˈβaða] ) is a landlocked state in the Western United States. It is also sometimes placed in the Mountain West and Southwestern United States. It borders Oregon to the northwest, Idaho to the northeast, California to the west, Arizona to the southeast, and Utah to the east. Nevada is the seventh-most extensive and the 31st-most populous U.S. state. Nearly three-quarters of Nevada\'s population live in Clark County, which contains the Las Vegas–Paradise metropolitan area. Nevada\'s capital is Carson City. Las Vegas is the largest city in the state. Nevada is officially known as the "Silver State" because of the importance of silver to its history and economy. It is also known as the "Battle Born State" because it achieved statehood during the Civil War; as the "Sagebrush State", for the native plant of the same name; and as the "Sage-hen State".',
  "New Hampshire":
    'New Hampshire ( HAMP-shər) is a state in the New England region of the Northeastern United States. It borders Massachusetts to the south, Vermont to the west, Maine and the Gulf of Maine to the east, and the Canadian province of Quebec to the north. Of the 50 U.S. states, New Hampshire is the seventh-smallest by land area and the tenth-least populous, with a population of 1,377,529 residents as of the 2020 census. Concord is the state capital and Manchester is the most populous city. New Hampshire\'s motto, "Live Free or Die", reflects its role in the American Revolutionary War; its nickname, "The Granite State", refers to its extensive granite formations and quarries. It is well known for holding the first primary in the U.S. presidential election cycle, and its resulting influence on American electoral politics.',
  "New Jersey":
    "New Jersey is a state located in both the Mid-Atlantic and Northeastern regions of the United States. Located at the geographic hub of the heavily urbanized Northeast megalopolis, it is bordered to the northwest, north, and northeast by New York State; on its east, southeast, and south by the Atlantic Ocean; on its west by the Delaware River and Pennsylvania; and on its southwest by Delaware Bay and Delaware. At 7,354 square miles (19,050 km2), New Jersey is the fifth-smallest state in land area. According to a 2024 U.S. Census Bureau estimate, it is the 11th-most populous state, with over 9.5 million residents, its highest estimated count ever. The state capital is Trenton, and the state's most populous city is Newark. New Jersey is the only U.S. state in which every county is deemed urban by the U.S. Census Bureau. It is the most densely populated U.S. state.",
  "New Mexico":
    "New Mexico is a landlocked state in the Southwestern region of the United States. It is one of the Mountain States of the southern Rocky Mountains, sharing the Four Corners region with Utah, Colorado, and Arizona. It also borders the state of Texas to the east and southeast, Oklahoma to the northeast, and shares an international border with the Mexican states of Chihuahua and Sonora to the south. New Mexico's largest city is Albuquerque, and its state capital is Santa Fe, the oldest state capital in the U.S.—founded in 1610 as the government seat of Nuevo México in New Spain—and the highest in elevation, at 6,998 feet (2,133 m). New Mexico is the fifth-largest of the fifty states by area, but with just over 2.1 million residents, ranks 36th in population and 45th in population density.",
  "New York":
    "New York, also called New York State, is a state located in the northeastern United States. Bordering the region of New England to its east, the country of Canada to the north, and Pennsylvania and New Jersey to the south, its territory extends into both the Atlantic Ocean and the Great Lakes. New York is the fourth-most populous state in the United States, with over 20 million residents, and the 27th-largest state by area, with a total area of 54,556 square miles (141,300 km2). New York has a varied geography. The southeastern part of the state, known as Downstate, encompasses New York City, the most populous city in the United States; Long Island, with approximately 40% of the state's population, the nation's most populous island; and the cities, suburbs, and wealthy enclaves of the lower Hudson Valley.",
  "North Carolina":
    "North Carolina ( KARR-ə-LY-nə) is a state in the Southeastern and South Atlantic regions of the United States. It is bordered by Virginia to the north, the Atlantic Ocean to the east, South Carolina to the south, Georgia to the southwest, and Tennessee to the west. The state is the 28th-largest and ninth-most populous of the United States. Along with South Carolina, it makes up the Carolinas region of the East Coast. At the 2020 census, the state had a population of 10,439,388. Raleigh is the state's capital and Charlotte is its most populous and one of the fastest growing cities in the United States. The Charlotte metropolitan area, with an estimated population of 2,883,370 in 2024, is the most populous metropolitan area in North Carolina, the 21st-most populous in the United States, and the largest banking center in the nation after New York City.",
  "North Dakota":
    "North Dakota ( də-KOH-tə) is a landlocked U.S. state in the Upper Midwest, named after the indigenous Dakota and Sioux peoples. It is bordered by the Canadian provinces of Saskatchewan and Manitoba to the north and by the U.S. states of Minnesota to the east, South Dakota to the south, and Montana to the west. North Dakota is part of the Great Plains region, characterized by broad prairies, steppe, temperate savanna, badlands, and farmland. North Dakota is the 19th-largest state by area, but with a population of just under 800,000, the fourth-least populous and fourth-least densely populated. The state capital is Bismarck and the most populous city is Fargo, which accounts for nearly a fifth of the state's population; both cities are among the fastest-growing in the U.S., although half of North Dakotans live in rural areas.",
  Ohio: 'Ohio ( oh-HY-oh) is a state in the Midwestern region of the United States. It borders the Canadian province of Ontario to the north (through Lake Erie), Pennsylvania to the east, West Virginia to the southeast, Kentucky to the southwest, Indiana to the west, and Michigan to the northwest. Of the 50 U.S. states, it is the 34th-largest by area. With a population of nearly 11.9 million, Ohio is the seventh-most populous and tenth-most densely populated state. Its capital and most populous city is Columbus, with other major metropolitan centers including Cleveland and Cincinnati, as well as Dayton, Akron, and Toledo. Ohio is nicknamed the "Buckeye State" after its Ohio buckeye trees, and Ohioans are also known as "Buckeyes".',
  Oklahoma:
    "Oklahoma ( OH-klə-HOH-mə; Choctaw: Oklahumma, pronounced [oklahómma]) is a landlocked state in the South Central and Southwestern region of the United States. It borders Texas to the south and west, Kansas to the north, Missouri to the northeast, Arkansas to the southeast, New Mexico to the west, and Colorado to the northwest. Partially in the western extreme of the Upland South, it is the 20th-most extensive and the 28th-most populous of the 50 United States. Its residents are known as Oklahomans and its capital and largest city is Oklahoma City. The state's name is derived from the Choctaw words okla, 'people' and humma, which translates as 'red'.",
  Oregon:
    "Oregon ( ORR-ih-ghən, -⁠gon) is a state in the Pacific Northwest region of the United States. It is a part of the western United States, with the Columbia River delineating much of Oregon's northern boundary with Washington, while the Snake River delineates much of its eastern boundary with Idaho. The 42° north parallel delineates the southern boundary with California and Nevada. The western boundary is formed by the Pacific Ocean. Oregon has been home to many indigenous nations for thousands of years. The first European traders, explorers, and settlers began exploring what is now Oregon's Pacific coast in the early to mid-16th century. As early as 1564, the Spanish began sending vessels northeast from the Philippines, riding the Kuroshio Current in a sweeping circular route across the northern part of the Pacific.",
  Pennsylvania:
    "Pennsylvania, officially the Commonwealth of Pennsylvania, is a state located in the Mid-Atlantic, Northeastern, Appalachian, and Great Lakes regions of the United States. It borders Delaware to its southeast, Maryland to its south, forming the Mason-Dixon Line, West Virginia to its southwest, Ohio to its west, the Canadian province of Ontario to its northwest via Lake Erie, New York to its north, and the Delaware River and New Jersey to its east. Pennsylvania's most populous city is Philadelphia, and the state capital is Harrisburg. Among all US states, Pennsylvania is the fifth-most populous with over 13 million residents as of the 2020 United States census, the ninth-highest by population density, and the 33rd-largest by land area.",
  "Rhode Island":
    "Rhode Island ( ROHD) is a state in the New England region of the Northeastern United States. It borders Connecticut to its west; Massachusetts to its north and east; and the Atlantic Ocean to its south via Rhode Island Sound and Block Island Sound; and shares a small maritime border with New York, east of Long Island. Rhode Island is the smallest U.S. state by area and the seventh-least populous, with slightly more than 1.11 million residents as of 2025. The state's population, however, has continually recorded growth in every decennial census since 1790, and it is the second-most densely populated state after New Jersey. The state takes its name from the eponymous island, though most of its land area is on the mainland. Providence is its capital and most populous city. Native Americans lived around Narragansett Bay before English settlers began arriving in the early 17th century.",
  "South Carolina":
    "South Carolina ( KARR-ə-LY-nə) is a state in the Southeastern, South Atlantic and Deep South regions of the United States. It borders North Carolina to the north and northeast, the Atlantic Ocean to the southeast, and Georgia to the west and south across the Savannah River. Along with North Carolina, it makes up the Carolinas region of the East Coast. South Carolina is the 11th-smallest and 23rd-most populous U.S. state with a recorded population of 5,118,425 according to the 2020 census. In 2019, its GDP was $213.45 billion. South Carolina is composed of 46 counties. The capital is Columbia with a population of 136,632 in 2020; while its most populous city is Charleston with a 2020 population of 150,227. The Greenville-Spartanburg-Anderson, SC Combined Statistical Area is the most populous combined metropolitan area in the state, with an estimated 2023 population of 1,590,636.",
  "South Dakota":
    'South Dakota ( ; Siouan languages: Dakȟóta itókaga, pronounced [daˈkˣota iˈtokaga]) is a landlocked state in the Upper Midwest, North Central region of the United States. It is also part of the Great Plains. South Dakota is named after the Dakota Sioux tribe, which comprises a large portion of the population and has historically dominated the territory. South Dakota is the 17th-largest by area, the fifth-least populous, and the fifth-least densely populated of the 50 United States. Pierre is the state capital, and Sioux Falls, with a population of about 213,900, is the most populous city. The Missouri River bisects the state into two geographically and socially distinct halves colloquially known as "East River" and "West River".',
  Tennessee:
    "Tennessee ( , locally ), officially the State of Tennessee, is a landlocked state in the Southeastern region of the United States. It borders Kentucky to the north, Virginia to the northeast, North Carolina to the east, Georgia, Alabama, and Mississippi to the south, Arkansas to the southwest, and Missouri to the northwest. Tennessee is the 36th-largest by area and the 15th-most populous of the 50 states. According to the United States Census Bureau, the state's estimated population as of 2024 is 7.22 million. Tennessee is geographically, culturally, and legally divided into three Grand Divisions of East, Middle, and West Tennessee. Nashville is the state's capital and largest city, and anchors its largest metropolitan area.",
  Texas:
    'Texas ( TEK-səss) is the most populous state in the Southern United States. It borders Louisiana to the east, Arkansas to the northeast, Oklahoma to the north, New Mexico to the west, and an international border with the Mexican states of Chihuahua, Coahuila, Nuevo León, and Tamaulipas to the south and southwest, that forms a natural boundary delineated by the Rio Grande. Texas has a coastline on the Gulf of Mexico to the southeast. Covering 268,596 square miles (695,660 km2) and with over 31 million residents as of 2024, it is the second-largest U.S. state by area and population. Texas is nicknamed the "Lone Star State" for the single star on its flag, symbolic of its former status as an independent country, the Republic of Texas. Spain was the first European country to claim and control Texas.',
  Utah: "Utah is a landlocked state in the Mountain West subregion of the Western United States. It is one of the Four Corners states, sharing a border with Arizona, Colorado, and New Mexico. It also borders Wyoming to the northeast, Idaho to the north, and Nevada to the west. In comparison to all the U.S. states and territories, Utah, with a population of just over three million, is the 13th-largest by area, the 30th-most populous, and the 11th-least densely populated. Urban development is mostly concentrated in two regions: the Wasatch Front in the north-central part of the state, which includes the state capital, Salt Lake City, and is home to roughly two-thirds of the population; and Washington County in the southwest, which has approximately 180,000 residents. Most of the western half of Utah lies in the Great Basin.",
  Vermont:
    "Vermont ( ) is a landlocked state in the New England region of the Northeastern United States. It borders Massachusetts to the south, New Hampshire to the east, New York to the west, and the Canadian province of Quebec to the north. According to the most recent U.S. census estimates, the state has an estimated population of 648,493, making it the second-least populated of all U.S. states. It is the nation's sixth-smallest state by total area. The state's capital of Montpelier is the least populous U.S. state capital. No other U.S. state has a most populous city with fewer residents than Burlington. Native Americans have inhabited the area for about 12,000 years. The competitive tribes of the Algonquian-speaking Abenaki and Iroquoian-speaking Mohawk were active in the area at the time of European encounter.",
  Virginia:
    "Virginia, officially the Commonwealth of Virginia, is a state in the Southeastern and Mid-Atlantic regions of the United States between the Atlantic Coast and the Appalachian Mountains. It borders Kentucky to the west, Tennessee to the south-west, North Carolina to the south, West Virginia to the north-west, and Maryland to the north. The state's capital is Richmond and its most populous city is Virginia Beach. With a population of 8.8 million, it is the twelfth-most populous and fifteenth-most densely populated state. More than one-third of Virginia's population lives in Northern Virginia, which includes the most populous jurisdiction in the state, Fairfax County. Eastern Virginia is part of the Atlantic Plain, and the Middle Peninsula forms the mouth of the Chesapeake Bay.",
  Washington:
    "Washington is a state in the Pacific Northwest region of the United States. It is often referred to as Washington state to distinguish it from the national capital, both named after George Washington, a U.S. Founding Father and the first U.S. president. Washington borders the Pacific Ocean to the west, Oregon to the south, and Idaho to the east and shares an international border with the Canadian province of British Columbia to the north. Olympia is the state capital, and the most populous city is Seattle. Washington is the 18th-largest state, with an area of 71,362 square miles (184,830 km2), and the 13th-most populous state, with a population of over 8 million.",
  "West Virginia":
    "West Virginia is a mountainous, landlocked state in the Southern and Mid-Atlantic regions of the United States. It is bordered by Pennsylvania and Maryland to the northeast, Virginia to the southeast, Kentucky to the southwest, and Ohio to the northwest. West Virginia is the 10th-smallest state by area and ranks as the 12th-least populous state, with a population of 1,769,979 residents. The capital and most populous city is Charleston with a population of 49,055. West Virginia was admitted into the Union on June 20, 1863, and was a key border state during the American Civil War. It separated from Virginia and was one of two states (along with Nevada) admitted to the Union during the Civil War. Some of its residents held slaves, but most were propertied farmers, and the delegates provided for the gradual abolition of slavery in the new state constitution.",
  Wisconsin:
    "Wisconsin is a state in the Upper Midwest and Great Lakes regions of the United States. It borders Minnesota to the west, Iowa to the southwest, Illinois to the south, Lake Michigan to the east, Michigan to the northeast, and Lake Superior to the north. With a population of about 6 million and an area of about 65,500 square miles (170,000 km2), Wisconsin is the 21st-largest state by population and the 23rd-largest by area. It has 72 counties. The state's most populous city is Milwaukee. Its capital and second-most populous city is Madison; other urban areas include Green Bay and the Fox Cities. Wisconsin's geography is diverse, with dense forests in the north (including Chequamegon–Nicolet National Forest), rugged unglaciated hills in the western Driftless Area, and wooded plains, lowlands, and farms stretching from the interior east to Lake Michigan.",
  Wyoming:
    "Wyoming ( wy-OH-ming) is a landlocked state in the Mountain West subregion of the Western United States. It borders Montana to the north and northwest, South Dakota and Nebraska to the east, Idaho to the west, Utah to the southwest, and Colorado to the south. With an estimated population of 587,618 as of 2024, Wyoming is the least populous state despite being the tenth-largest by area, and it has the second-lowest population density. The state capital and most populous city is Cheyenne. Wyoming's western half consists mostly of the ranges and rangelands of the Rocky Mountains; its eastern half consists of high-elevation prairie, and is referred to as the High Plains. Wyoming's climate is semi-arid in some parts and continental in others, making it drier and windier overall than other states, with greater temperature extremes.",
};
